#!/usr/bin/env ruby

require 'square'

# TODO include speed, color_width
if (position = ARGV[0] =~ /hue=/)
  hue_start = position + 'hue='.length
  if (hue = ARGV[0][hue_start..-1].to_i) > 0
    Vertex.hue = hue
    Vertex.color_width = 100
  end
end

# TODO maybe load a text-based graph
g = Graph::Square.new(n: 20)

g.add_hori_barrier(i: 2, j: 0, size: 18)
g.add_hori_barrier(i: 6, j: 5, size: 15)
g.add_hori_barrier(i: 10, j: 0, size: 18)
g.add_hori_barrier(i: 14, j: 5, size: 15)
g.add_vert_barrier(i: 14, j: 5, size: 5)

g.print_vertices(speed: 150)

